# Generated by Django 3.0.3 on 2020-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_clicked_subgroup_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
