# Generated by Django 3.0.3 on 2020-06-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_clicked_subgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_clicked_subgroup_name',
        ),
        migrations.CreateModel(
            name='Last_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_clicked_subgroup_name', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
