# Generated by Django 3.0.3 on 2020-06-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200621_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Last_location',
        ),
    ]
