# Generated by Django 3.0.3 on 2020-06-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0002_auto_20200620_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at']},
        ),
    ]
