# Generated by Django 3.0.3 on 2020-06-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0004_reply_last_clicked_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='last_clicked_pk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
