# Generated by Django 3.0.3 on 2020-06-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
