# Generated by Django 3.0.3 on 2020-06-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgroups', '0002_auto_20200620_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
